# Generated by Django 4.1.1 on 2022-09-28 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0008_follow_alter_profile_slug_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user_from', 'user_to')},
        ),
    ]
