# Generated by Django 4.1.1 on 2022-09-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whisper', '0003_alter_whisper_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisper',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='likes')),
                ('whisper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whisper.whisper', verbose_name='likes')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
