# Generated by Django 4.1.1 on 2022-09-29 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whisper', '0004_remove_whisper_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=0, verbose_name='Liked'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='like',
            name='whisper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='whisper.whisper', verbose_name='likes'),
        ),
    ]
